// This file is automatically generated. Do not modify it.
import { FirebaseOptions } from "firebase/app";

// Your web app's Firebase configuration
// This is a public configuration and it is safe to expose this.
// Security is enforced by your Firebase Security Rules.
export const firebaseConfig: FirebaseOptions = {
  "apiKey": "your-api-key",
  "authDomain": "your-project-id.firebaseapp.com",
  "projectId": "your-project-id",
  "storageBucket": "your-project-id.appspot.com",
  "messagingSenderId": "your-messaging-sender-id",
  "appId": "your-app-id",
  "measurementId": "your-measurement-id"
};
